name = "leafwing_input_manager"
description = "Manage action states and input mapping across input devices. Fully documented; exceptionally ergonomic."
link = "https://crates.io/crates/leafwing-input-manager"
