name = "leafwing_input_manager"
description = "Manage action states and input mapping in a configurable, device-agnostic fashion. Fully documented; exceptionally ergonomic."
link = "https://crates.io/crates/leafwing-input-manager"
